def generate_exception():
    result = 10 / 0  # This will cause a ZeroDivisionError
    print(result)
generate_exception()
