def generate_arithmetic_exception():
    result = 10 / 0  # This will cause a ZeroDivisionError
    print(result)

# Call the function
generate_arithmetic_exception()
